wandb_version: 1

learning_rate:
  desc: null
  value: 0.07371911108130276
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 64
gamma:
  desc: null
  value: 0.7
seed:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709559512.943699
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.10
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
